<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

class BaseAR extends BaseARUnTime
{

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'add_time',//根据数据库字段修改
                'updatedAtAttribute' => 'update_time',//根据数据库字段修改
                'value' => time(),
            ],
        ];
    }

    public static function updateAll($attributes, $condition = '', $params = [])
    {
        $attributes['update_time'] = time();
        return parent::updateAll($attributes, $condition, $params); // TODO: Change the autogenerated stub
    }


    /**
     * @return array
     * @throws \yii\base\InvalidConfigException
     */
    public function fields()
    {
        $fields = parent::fields();
        $this->add_time= Yii::$app->formatter->asDatetime($this->add_time);
        $this->update_time= Yii::$app->formatter->asDatetime($this->update_time);
        return $fields;
    }

}
