<?php
namespace common\services\goods\platform;

use common\components\CommonUtil;
use common\components\statics\Base;
use common\models\goods\GoodsHepsiglobal;
use common\models\GoodsSource;
use yii\base\Exception;

class HepsiglobalPlatform extends BasePlatform
{

    /**
     * 是否支持html
     * @var bool
     */
    public $html = true;

    /**
     * 语言
     * @var string
     */
    public $platform_language = 'tr';

    public static $colour_map = [
        'Black'=>'Siyah',
        'White'=>'Beyaz',
        'Grey'=>'Gri',
        'Transparent'=>'Şeffaf',
        'Red'=>'Kırmızı',
        'Pink'=>'Pembe',
        'Wine red'=>'Şarap kırmızısı',
        'Blue'=>'Mavi',
        'Green'=>'Yeşil',
        'Purple'=>'Mor',
        'Yellow'=>'Sarı',
        'Beige'=>'Bej',
        'Brown'=>'Kahverengi',
        'Khaki'=>'Haki',
        'Orange'=>'Turuncu',
        'Rose gold'=>'Gül altın',
        'Gold'=>'Altın',
        'Silver'=>'Gümüş',
        'Copper'=>'Bakır',
        'Colorful'=>'Renkli',
        'Wood'=>'Ahşap',
    ];

    /**
     * 商品model
     * @return mixed
     */
    public function model()
    {
        return new GoodsHepsiglobal();
    }

    /**
     * 获取价格
     * @param array|mixed $goods 商品
     * @param int|null $shop_id 店铺id
     * @return float
     * @throws Exception
     */
    public function getPrice($goods,$shop_id = null)
    {
        if ($this->isFollowSource($goods)) {
            $follow_price = GoodsSource::find()
                ->where(['platform_type' => Base::PLATFORM_HEPSIGLOBAL, 'goods_no' => $goods['goods_no']])
                ->select('price')->scalar();
            if ($follow_price > 0) {
                return $this->followPrice($follow_price, $shop_id);
            }
        }
        return parent::getPrice($goods, $shop_id);
    }

    /**
     * 跟卖价格处理
     * @param $he_price
     * @param $shop_id
     * @return float
     */
    public function followPrice($he_price,$shop_id = null)
    {
        //最高价格=(hepis价格/19-1.603-11*重量-0.3)/2.0053*6.3
        $he_price = $he_price - 10;
        $goods = $this->goods;
        $weight = empty($goods['real_weight']) ? $goods['weight'] : $goods['real_weight'];
        return ($he_price / 19 - 1.603 - 11 * $weight - 0.3) / 2.0053;
    }

    /**
     * 价格处理
     * 运费= 重量/0.5 * 10 + 35
     * 售价=（成本*1.7+运费）1.13/4.5
     * @param double $weight 重量
     * @param double $albb_price 阿里巴巴价格
     * @param string $size 尺寸
     * @param int|null $shop_id 店铺id
     * @return float
     */
    public function treatmentPrice($weight,$albb_price,$size = '',$shop_id = null)
    {
        //$weight = $this->getWeight($weight, $size, 6000);
        //$freight = ceil($weight / 0.5) * 10 + 35;
        //$price = ($freight + $albb_price * 1.7) * 1.13/4.5;
        if(!in_array($shop_id,[471,472])) {
            $price = $this->tieredPricing1($albb_price);
            return $price/7;
        }
        $price = 0;
        $price_b = [
            300 => 1.4,
            200 => 1.6,
            100 => 1.7,
            50 => 1.8,
            35 => 2,
            25 => 2.3,
            15 => 2.5,
            0 => 3,
        ];
        foreach ($price_b as $k=>$v) {
            if ($albb_price > $k) {
                $price_tmp = $albb_price - $k;
                $price += $price_tmp * $v;
                $albb_price = $albb_price - $price_tmp;
            }
        }
        //$albb_price = $albb_price <= 25 ? ($albb_price + 10) : $albb_price;
        //$price = $albb_price * 1.8 / 6.3;
        $price = $price / 7;
        $zk = 0.8;
        if($albb_price > 200) {//大于200 按9折算
            $zk = 0.9;
        }
        return $price * $zk;
    }

    public function dealTitle($name)
    {
        $name = CommonUtil::filterTrademark($name);
        return $this->filterContent($name);
    }

    public function filterContent($content)
    {
        $map = [
            "2. Kalite",
            "A Kalite",
            "a long time",
            "abdullah ocalan",
            "abdullah öcalan",
            "Absolut",
            "actıon",
            "adet ağrıları",
            "adet ağrısı",
            "adıtennıs",
            "aegına",
            "Afrodizyak",
            "ağrı bandı",
            "ağrı bantı",
            "ağrı giderici",
            "ağrı gidermeye",
            "Ağrı Kesici",
            "ağrı pedi",
            "ağrı tedavisinde",
            "ağrıları giderici",
            "ağrılarını giderir",
            "ağrılarını gidermeye",
            "ağrıyı azaltan",
            "Airsoft",
            "aladdın",
            "allıance",
            "Altıncezve",
            "alumnı",
            "Amazon E-kitap",
            "Amazon Kindle",
            "Amazon Kindle Touch",
            "Amazon New Touch",
            "Amazon Paperwhite",
            "Amazon Touch",
            "Amazon Voyage",
            "amino asit",
            "aminoacid",
            "aminoasit",
            "Anal Daraltıcı Krem",
            "Anal Daraltıcı sprey",
            "Anal uyarıcı Krem",
            "Anal uyarıcı sprey",
            "Anti baktariyel",
            "Antibaktariyal",
            "Antifungal",
            "Antimikrobiyal",
            "Antimikrobiyel",
            "asorti",
            "Aspirasyon",
            "Aşk Damlası",
            "Ateş Düşürücü",
            "Atomizör",
            "avrat",
            "Azdırıcı",
            "bacardi",
            "Backpak",
            "bakteri",
            "banyo tuzu",
            "banyotuzu",
            "Bardak Çekme",
            "basıc",
            "baş ağrıları",
            "baş ağrısı",
            "bel ağrıları",
            "bel ağrısı",
            "bel ağrısına",
            "Bepanthol sensıderm",
            "Bepanthol Sensiderm",
            "bıt",
            "Bıt Spreyi",
            "Bıt Şampuanı",
            "Bıt-Sırke",
            "biber gaz",
            "biber gazı",
            "Bit - Sirke",
            "Bit Kovucu",
            "Bit Spreyi",
            "Bit Şampuanı",
            "Bit ve Sirke",
            "Bit-Sirke",
            "boyun korsesi",
            "Buyutucu",
            "Büyütücü",
            "Camel Active",
            "caprı",
            "casus camera",
            "casus kamera",
            "cınteo",
            "Cıstus",
            "Cıtcıtlı",
            "cıty",
            "Cinsel İstek Arttırıcı",
            "Cistus",
            "clasıc",
            "classıc",
            "clımacool",
            "Cml Active",
            "Cocaine",
            "Corona virüs",
            "Coronavirus",
            "coronaya karşı",
            "Covid19",
            "Covid-19",
            "cushıon",
            "çok satan",
            "daıly",
            "Daraltıcı Krem",
            "Defibrilatör",
            "Delay",
            "delay 48000",
            "Delay krem",
            "delay sprey",
            "derin tarih",
            "Dezenfekte Eder",
            "dıpdye",
            "dıstance",
            "dıve",
            "dıvısıon",
            "Diabetik",
            "dik duruş",
            "Dik Duruş Korsesi",
            "dik duruş yeleği",
            "dinleme cihazı",
            "dorso lomber",
            "dorsolomber",
            "doublewıde",
            "downshıfter",
            "Drı Fıt",
            "drıfıt",
            "drı-fıt",
            "Dudak Büyüten",
            "Dudak Büyütücü",
            "Dugun Parası",
            "Dugun Parasi",
            "düğün doları",
            "düğün eurosu",
            "düğün lira",
            "düğün lirası",
            "düğün parası",
            "dynamıc",
            "eklem ağrıları",
            "eklem ağrılarına",
            "eklem ağrısı",
            "Elektrikli Şok Cihazı",
            "elektro sok",
            "elektro sqk",
            "elektro şok",
            "Elektro Şok Tasma",
            "Elektro Şoklu Tasma",
            "elektrosok",
            "elektroşok",
            "elektroşok cihazı",
            "Elektroşok Tasma",
            "elektrq sqk",
            "elıte",
            "embroıdered",
            "Endeskobi",
            "Endeskobi Dezenfektanı",
            "Endeskopi",
            "Engelli Yatağı",
            "Eoprotın",
            "Eoprotin",
            "Erection",
            "Ereksiyon",
            "Ereksiyon Jeli",
            "Ereksiyon Sağlayıcı",
            "Erkek Azdırıcı",
            "Erken boşalma",
            "Erken boşalmayı önleyici",
            "Esofman",
            "F.E.T.O",
            "F.E.T.Ö",
            "Featherlıght",
            "Fethullah Gülen",
            "Feto",
            "Fetö",
            "Fettullah Gulen",
            "Fettullah Gülen",
            "Fetullah Gulen",
            "Fetullah Gülen",
            "Fıerce",
            "Fılament",
            "fırebırd",
            "fıve",
            "flyknıt",
            "fuck",
            "fungisit",
            "fusıon",
            "gebelik testi",
            "Geciktirici",
            "Geciktirme kremi",
            "Geciktirme spreyi",
            "genıcco",
            "genıo",
            "gırevık",
            "gırl",
            "gizli camera",
            "Gizli Kamera",
            "glukozamin",
            "Göğüs Büyütücü",
            "Göğüs Dikleştirici",
            "göz damlası",
            "göz jeli",
            "graphıc",
            "grıd",
            "grıp",
            "Guıld",
            "hacamat",
            "Hasta Yatağı",
            "Hastalığa karşı",
            "Havai Fişek",
            "havaifişek",
            "Havalı Silah",
            "Havalı Tabanca",
            "Havalı Tüfek",
            "havlama onleyıcı",
            "havlama onleyici",
            "havlama önleyıcı",
            "Havlama Önleyici",
            "heıghts",
            "Hepsiburada Home",
            "Hepsiburadahome",
            "herbisit",
            "hero baskılı tshirt",
            "hero baskılı t-shirt",
            "hero logolu tshirt",
            "hero logolu t-shirt",
            "hero tshirt",
            "hero t-shirt",
            "hybrıd",
            "hyperelıte",
            "Ilaclama Pompası",
            "ınfınıte",
            "Invıgor",
            "ısolatıon",
            "İkinci Kalite",
            "ilacı",
            "İlaçlama",
            "ilaçlama makinası",
            "ilaçlama makinesi",
            "İlaçlama Pompası",
            "İlişki Süresini Uzatan",
            "imaj gözlüğü",
            "imitasyon",
            "indirimli",
            "insektisit",
            "İpek Yolu Baharat",
            "İstek arttırıcı jel",
            "İstek Arttırıcı Uyarıcı",
            "j&b",
            "Jeunesse",
            "kaıshı",
            "Kalça Büyütür",
            "Kalça Dikleştirici",
            "kamburluk",
            "kamburluk önleyici",
            "Kampanya",
            "Kampanyalı",
            "kampanyası",
            "Kaprı",
            "karambıt",
            "Karambit",
            "karnitin",
            "kemer susturucu",
            "kemer yukseltıcı",
            "kemer yükseltici",
            "kıck",
            "kıds",
            "Kındle",
            "kınect",
            "kıtmir",
            "kıvılcım sacar",
            "Kıvılcım Saçar",
            "kıvılcımsacar",
            "kıvılcımsaçar",
            "Kız Kacıran",
            "Kız Kaçıran",
            "kızkacıran",
            "kızkaçıran",
            "Kilo aldırıcı",
            "kilo aldırır",
            "Kilo Verdirici",
            "kilo verdirir",
            "Kindle",
            "Kindlee",
            "kinesiology",
            "knıt",
            "Kokain",
            "kolossal cream",
            "Komili Konfor",
            "Kormilin",
            "korona",
            "Kortiram",
            "Körfezim",
            "Kupa Çekme",
            "Kupa Çekme Seti",
            "kus konmaz",
            "Kus Kovan",
            "Kus Kovar",
            "Kus Kovucu",
            "Kuş Kovan",
            "Kuş Kovar",
            "Kuş Kovucu",
            "Leggıng",
            "Lens Solusyonu",
            "Lens Solüsyonu",
            "Lentıcular",
            "lıbretto",
            "lıft",
            "lıghtswıtch",
            "lıghtweıght",
            "Lımıtless",
            "lıne",
            "lıte",
            "Longtime",
            "lunareclıpse",
            "lunarglıde",
            "lykın",
            "Maç Meşalesi",
            "magısta",
            "majestıc",
            "Marquıs",
            "Matador",
            "Matchfıt",
            "matrıx",
            "Matyap",
            "Maytabı",
            "maytabi",
            "Maytap",
            "Maytapı",
            "maytapi",
            "mazlum ayı",
            "mazlum ayıcık",
            "Medikal Boyunluk",
            "Medikal Dizlik",
            "mercurıal",
            "Mesale",
            "Mesalesı",
            "Mesalesi",
            "meşale",
            "Meşalesı",
            "Meşalesi",
            "Metabolizma Hızlandırıcı",
            "mıcoach",
            "mıdıru",
            "mıdlayer",
            "mıler",
            "mıller",
            "Million Pauline",
            "moıre",
            "mystıfy",
            "Narcos",
            "Narkos",
            "Narkoz",
            "Nasır Bandı",
            "Nasır Bantı",
            "Nasır Yakı",
            "Nasır Yakısı",
            "nato biber",
            "nebulızator",
            "nebulizator",
            "nebulizatör",
            "nebulizor",
            "nebülızatör",
            "Nıght",
            "nıkel",
            "nike nike",
            "Ninja Panda",
            "Nitrat",
            "novexpert",
            "Numaralı Gozluk",
            "Numaralı Gözlük",
            "Numaralı Lens",
            "oksijen konsantratörü",
            "okuma gözlüğü",
            "omega3 balık yağı",
            "omega-3 balık yağı",
            "Omer Halis",
            "Omer Halis Demir",
            "omerhalis",
            "OmerHalisDemir",
            "Onarılmış",
            "Orgazm",
            "Orgazm Kremi",
            "Orgazm spreyi",
            "orijinal",
            "orjinal",
            "ortam dinleme",
            "Ortopedik",
            "ovıled",
            "ovülasyon",
            "öcalan",
            "Ömer Halis",
            "ömer halis demir",
            "Ömer Halis Demir",
            "Ömer Halisdemir",
            "ömerhalis",
            "ÖmerHalis",
            "ömerhalisdemir",
            "ÖmerHalisDemir",
            "Paperwhite",
            "Paperwhite E-Kitap",
            "patlayan",
            "patlayan sigara",
            "Penis Büyütücü",
            "Penis Enlargement",
            "Penis Sertleştirici",
            "Performans Artırıcı",
            "Performans Arttırıcı",
            "pıco",
            "pıque",
            "pıtch",
            "pıvot",
            "pire spreyi",
            "pire tasması",
            "polyknıt",
            "posturex",
            "precısıon",
            "Pregomın",
            "Pregomin",
            "Prematil",
            "premıer",
            "premıum",
            "prıme",
            "prınt",
            "prınted",
            "prıorıty",
            "prodıgy",
            "pulseoksimetre",
            "Pulvarizatörü",
            "pulverizatör",
            "pursuıt",
            "pülverizatör",
            "ramans dooz 14000",
            "recertified",
            "refurbished",
            "Relax 30",
            "remıx",
            "respirometre",
            "retraksiyon",
            "retraksiyon harnesi",
            "revolutıon",
            "rıse",
            "rıval",
            "rıvalry",
            "rodrıguez",
            "Rolling Stones",
            "romatizmal",
            "rookıe",
            "Roubaıx",
            "runnıng",
            "Saka Lira",
            "serıe",
            "Sertleştirici",
            "sex",
            "shıeldrunner",
            "shıne",
            "sıgnal",
            "Sıgnature",
            "sınglet",
            "sıs bombası",
            "sıs bombasi",
            "Sidra",
            "siktir",
            "silah",
            "Sim Card",
            "Sim Card Girişi",
            "Sim Kart",
            "Sim Kart Girişi",
            "sis bombası",
            "sis bombasi",
            "Sivrisinek İlacı",
            "Skılls",
            "skırt",
            "slıp",
            "smart watch",
            "smartwatch",
            "smıth",
            "Sok Cihazı",
            "solıd",
            "Solstıce",
            "spacial",
            "sprınt",
            "Stadıum",
            "stag 9000",
            "stag geciktirici sprey",
            "Stag9000",
            "statıc",
            "steteskop",
            "Stetoskop",
            "Stg9000",
            "strıpe",
            "strıped",
            "suıt",
            "Sylvia Ritter",
            "Şaka Lira",
            "şeker ölçüm",
            "şeker ölçüm cihazı",
            "şeker ölçüm stribi",
            "Şok Cihazı",
            "taılwınd",
            "taldex",
            "Tarım İlacı",
            "Tarım İlaci",
            "Tarim İlaci",
            "teff tohumu",
            "tens aleti",
            "tens cihazı",
            "The Roling Stones",
            "The Rolling Stones",
            "Themra",
            "Thırd",
            "tıempo",
            "tıght",
            "tıme",
            "tıro",
            "titan gel",
            "titan jel",
            "t-lıte",
            "tokı",
            "Tonimer",
            "torpil",
            "tracksuıt",
            "tradıtıon",
            "traın",
            "traıner",
            "traınıng",
            "trıax",
            "trıbute",
            "t-short",
            "twıst",
            "ucuz",
            "valgus",
            "Varis",
            "varis çorabı",
            "varsıty",
            "velocı",
            "Veraolive",
            "Verbıage",
            "Versace 19.69 Abbigliamento Sportivo Srl.",
            "Versace 19V69",
            "Versace Jeans",
            "versatılıty",
            "vıctory",
            "vıntage",
            "Vıtal",
            "Vıvıd",
            "vıxen",
            "viga 100000",
            "viga 50000",
            "viga 60000",
            "Virüse karşı",
            "Volkan",
            "volkanı",
            "volkani",
            "whıte",
            "Whiskey",
            "Wıldhorse",
            "Wındrunner",
            "wınger",
            "wınter",
            "Wıthout",
            "Wrıst",
            "wrıstbands",
            "Yağ Yakan",
            "Yağ Yakıcı",
            "Zayıflatıcı",
            "jack daniels",
            "Jack Daniel's",
            "Jack Danies",
            "jackdaniel' s",
            "jackdaniels",
            "jackdaniel's",
            "jck daniels",
            "jck daniel's",
            "850",
            "2. el",
            "Alış fiyatı",
            "amazon",
            "amazon.com",
            "amazon.com.tr",
            "antiseptik",
            "Aras",
            "aras kargo",
            "Ayen Software",
            "Aynı gün gönderim",
            "Aynı gün kargo",
            "Aynı Gün Kargolanır",
            "Aynı Gün Kargoya",
            "Aynı gün kargoya teslim",
            "Aynı gün ücretsiz kargo",
            "Bedava",
            "Bedava aynı gün kargo",
            "Bedava kargo",
            "corona virus",
            "coronavirüs",
            "coronavirüsü",
            "covid",
            "covid 19",
            "Detay sayfası",
            "elektronik sigara",
            "entegra",
            "epttavm",
            "Ertesi gün gönderim",
            "facebook",
            "Fiyat listesi",
            "gittigidiyor",
            "gittigidiyor.com",
            "Hemen gönderim",
            "İletişim No",
            "İletişim Numarası",
            "İnanılmaz fiyat",
            "İnceltir",
            "İndirimli fiyat",
            "İndirimli satış",
            "instagram",
            "İrtibat",
            "Kampanyalı fiyat",
            "Kargo bedava",
            "Kargo ücreti",
            "Kargo ücretsiz",
            "Kargolanır",
            "knife",
            "Kutusuz",
            "Liste fiyatı",
            "Long time",
            "mail",
            "mikropları öldürür",
            "mng kargo",
            "morhipo",
            "Mostar",
            "Müşteri Temsilcisi",
            "n11",
            "n11.com",
            "Piyasa satış fiyatı",
            "PTT",
            "ptt kargo",
            "Rakiplerimiz",
            "Replica",
            "Replika",
            "satışımız",
            "Sayfamızdan",
            "Sitemizden",
            "Stok fazlası",
            "Stoktan satış",
            "süper fiyat",
            "Sürat kargo",
            "Tamir Görmüş",
            "tarafından gönderilecektir",
            "Telefon no",
            "Temsilci",
            "ticimax",
            "toptan",
            "Toptan satış",
            "trendyol",
            "trendyol.com",
            "tüm hakları saklıdır",
            "twitter",
            "Ucuz fiyat",
            "Ulaşın",
            "ücretsiz iade",
            "Ücretsiz kargo",
            "Ücretsiz ve aynı gün kargo",
            "Üretimden satış",
            "Ürün Açıklama sayfası",
            "Ürün fiyatı",
            "Websitemizden",
            "whatsapp",
            "Yarı fiyat",
            "youtube",
            "Yurtiçi",
            "Zararına satış",
            "Zayıflatır",
            "hepsiburada",
            "2. Quality",
            "absolute",
            "action",
            "menstrual pains",
            "menstrual pain",
            "nametennis",
            "aegina",
            "Aphrodisiac",
            "pain tape",
            "pain reliever",
            "to relieve pain",
            "Painkiller",
            "pain pad",
            "in the treatment of pain",
            "relieves pain",
            "pain reducing",
            "you cheated",
            "alliance",
            "alumni",
            "Amazon Ebook",
            "amino acid",
            "Anal Constricting Cream",
            "Anal Narrowing Spray",
            "Anal stimulating Cream",
            "anal stimulant spray",
            "antimicrobial",
            "Antiseptic",
            "assortment",
            "aspiration",
            "Love Drop",
            "splint",
            "Fever Reducer",
            "atomizer",
            "wife",
            "arousing",
            "bacterium",
            "bath salt",
            "bathsalt",
            "Cupping",
            "headaches",
            "headache",
            "bit",
            "Bit Spray",
            "Bit Shampoo",
            "Bit-vinegar",
            "pepper spray",
            "pepper gas",
            "Lice - Vinegar",
            "Lice Repeller",
            "Lice Spray",
            "Lice Shampoo",
            "Lice and Vinegar",
            "neck corset",
            "Enlarger",
            "capri",
            "spy camera",
            "cinteo",
            "Sexual Desire Enhancer",
            "against corona",
            "bestseller",
            "Narrowing Cream",
            "defibrillator",
            "Delay cream",
            "delay spray",
            "deep history",
            "Disinfects",
            "dipdye",
            "diabetic",
            "upright posture",
            "Upright Corset",
            "upright vest",
            "Listening device",
            "dorsal lumbar",
            "doublewide",
            "downshifter",
            "Lip Augmentation",
            "Lip Enhancer",
            "Wedding Money",
            "wedding dollar",
            "wedding euro",
            "wedding lira",
            "wedding pound",
            "joint pain",
            "electric shock device",
            "electroshock",
            "electro sqk",
            "Electro Shock Leash",
            "Electro Shock Collar",
            "shocker",
            "Electroshock Leash",
            "electrq sqk",
            "elite",
            "embroidered",
            "Seat Belt Adapter",
            "Seat Belt Bottle Opener",
            "Seat Belt Buckle",
            "Seat Belt Booster",
            "Seat Belt Upgrade",
            "endoscopy",
            "Endoscopy Disinfectant",
            "Disabled Bed",
            "eoprotine",
            "Erection Gel",
            "Erection Provider",
            "Male Enhancer",
            "premature ejaculation",
            "prevent premature ejaculation",
            "F.E.T.O.",
            "Featherlight",
            "Fethullah Gulen",
            "Fierce",
            "filament",
            "firebird",
            "price",
            "prices",
            "flyknit",
            "fungicide",
            "fusion",
            "guarantee",
            "pregnancy test",
            "retarder",
            "genicco",
            "genio",
            "crooked",
            "hidden camera",
            "Secret camera",
            "glucosamine",
            "Breast Enhancer",
            "Breast Lift",
            "eye drop",
            "eye gel",
            "grid",
            "flu",
            "Guild",
            "Patient Bed",
            "against disease",
            "hashem",
            "Fireworks",
            "Air Gun",
            "Airgun",
            "Air rifle",
            "bark preventer",
            "anti bark",
            "Anti-Bark",
            "heights",
            "herbicide",
            "hero print tshirt",
            "hero printed t-shirt",
            "hero logo tshirt",
            "hero logo t-shirt",
            "Spraying Pump",
            "Invigor",
            "isolation",
            "luminous",
            "luminescent",
            "Second Quality",
            "medicine",
            "Spraying",
            "sprayer",
            "Extending Relationship Duration",
            "image glasses",
            "imitation",
            "discount",
            "insecticide",
            "Silk Road Spices",
            "craving enhancer gel",
            "Desire Enhancer Stimulant",
            "Hips Enlarge",
            "Hip Lifter",
            "humpback",
            "anti-humpback",
            "Offer",
            "With a campaign",
            "campaign",
            "carnitine",
            "belt muffler",
            "belt riser",
            "kinect",
            "scatter sparks",
            "Sparks Sparks",
            "it sparks",
            "sparksacar",
            "sparkscatter",
            "Kidnapper",
            "hijacker",
            "weight gainer",
            "weight gain",
            "Weight Loss",
            "makes you lose weight",
            "knt",
            "colossal cream",
            "Komili Comfort",
            "corona",
            "my bay",
            "Cup Draw",
            "Mug Pull Set",
            "do not vomit",
            "Bird Hive",
            "Kuvar Kovar",
            "Bird Repellent",
            "Bird Repels",
            "Bird Repeller",
            "Prevents Mold",
            "Mold Prevention",
            "legging",
            "Lens Solution",
            "Lenticular",
            "libretto",
            "lift",
            "lightswitch",
            "lightweight",
            "limitless",
            "lite",
            "lunareclipse",
            "in lunargli",
            "lykin",
            "Match Torch",
            "magista",
            "majestic",
            "marquis",
            "matchfit",
            "matrix",
            "Drill",
            "sparkler",
            "Squib",
            "oppressed bear",
            "oppressed teddy bear",
            "Medical Collar",
            "Medical Knee Brace",
            "mercurial",
            "Torch",
            "for example",
            "the matter",
            "Metabolism Booster",
            "micoach",
            "Germ is Dead",
            "Kills Germs",
            "moire",
            "Examination Gloves",
            "mystify",
            "Narcosis",
            "Callus Tape",
            "Callus Patch",
            "nato pepper",
            "nebulizer",
            "nickel",
            "Nitrate",
            "Numbered Eyeglasses",
            "Prescription Glasses",
            "Numbered Lens",
            "oxygen concentrator",
            "reading glasses",
            "omega3 fish oil",
            "omega-3 fish oil",
            "Orgasm",
            "Orgasm Cream",
            "orgasm spray",
            "original",
            "Listening to media",
            "Orthopedic",
            "ovulated",
            "ovulation",
            "the revenger",
            "Omer Halisdemir",
            "euphoria",
            "Paperwhite E-Book",
            "Paradise",
            "exploding",
            "exploding cigarette",
            "Penis Enlarger",
            "Penis Hardener",
            "Performance Enhancer",
            "pico",
            "pique",
            "pitch",
            "pivot",
            "flea spray",
            "flea collar",
            "polyknit",
            "precion",
            "pregmin",
            "pregomine",
            "premature",
            "premier",
            "premium",
            "prime",
            "print",
            "printed",
            "priority",
            "prodigy",
            "pulseoximeter",
            "pulverizer",
            "pursuit",
            "remix",
            "respirometer",
            "retraction",
            "retraction belt",
            "revolution",
            "rheumatic",
            "rookie",
            "roubaix",
            "serie",
            "Hardener",
            "Back Support Corset",
            "smoke bomb",
            "weapon",
            "Sim Card Login",
            "Sim Card Input",
            "Mosquito Repellent",
            "smith",
            "Shock device",
            "solid",
            "Solstice",
            "sprint",
            "my stadium",
            "stag delay spray",
            "static",
            "stethoscope",
            "stripe",
            "striped",
            "suite",
            "Joke Lira",
            "glucometer",
            "glucometer strip",
            "crown by crystal",
            "Crown Crystal",
            "tailwind",
            "Pesticide",
            "teff seed",
            "tense device",
            "tens device",
            "titanium gel",
            "torpedo",
            "Twist",
            "compression stockings",
            "Verbiage",
            "against virus",
            "Volcano",
            "wildhorse",
            "windrunner",
            "winger",
            "Fat Burner",
            "attenuator",
            "2nd hand",
            "Purchase price",
            "between cargo",
            "same day shipping",
            "Ships Same Day",
            "On the same day free shipping",
            "Free",
            "Free same day shipping",
            "free shipping",
            "detail page",
            "electronic cigarette",
            "integrated",
            "Next day shipping",
            "factory sale",
            "Price list",
            "it's going",
            "gitgidiyor.com",
            "Immediate shipping",
            "Fast shipping",
            "fast delivery",
            "Contact Number",
            "Incredible price",
            "thins out",
            "Discounted price",
            "Bargain sale",
            "Contact",
            "Campaign price",
            "Free cargo",
            "Shipping fee",
            "Ships",
            "without box",
            "Prevents mold bacteria and germ formation",
            "prevents mildew",
            "List price",
            "mng cargo",
            "Customer Representative",
            "Repaired",
            "market selling price",
            "ptt cargo",
            "Our competitors",
            "our sale",
            "from our page",
            "from our site",
            "Overstock",
            "sale from stock",
            "super price",
            "speed cargo",
            "will be sent by",
            "Phone number",
            "Representative",
            "timax",
            "wholesale",
            "all rights reserved",
            "Cheap price",
            "free returns",
            "Free and same day shipping",
            "Sales from production",
            "Product Description page",
            "Product price",
            "from our website",
            "half price",
            "Domestic",
            "sale at a loss",
            "weakens",
            "Writing",
            "entrances",
            "Welcome To Our Store",
            "We Are Honored To Serve",
            "A Nice Gift For Your Wife, Daughter",
            "Owner Site Addresses",
            "Addresses of Social Media Accounts",
            "Drop Shipping",
            "Yes",
            "Next Day Cargo",
            "High Priced",
            "Trustworthy",
            "High quality",
            "Hemp",
            "Tencel",
            "Thanks",
            "Cargo",
            "Fee",
            "Contact us",
            "Social Media Platform names",
            "airpods",
            "shake",
            "wedge",
            "disinfect",
            "quick test",
            "Firework",
            "sex ",
            "ass",
            "pussy",
            "quality",
            "butterfly",
            "sword",
            "frontline",
            "jop",
            "drug",
            "smart watch (with spaces)",
            "e-book",
            "ceresto",
            "back pain",
            "lord",
            "kaliteli",
            "kişiye özel",
            "fiyat",
            "elf",
            "çıplak",
            "origin",
            "menşei",
            "virgin",
            "ucuz",
            "menşe",
            "fantezi",
            "yerel",
            "ikinci el",
            "second hand",
            "yurt dışından",
            "abroad",
            "sırt ağrısı",
            "Enayi",
            "remado",
            "swico",
            "Sell Global",
            "battery",
            "batteries",
            "Thank you",
            "thank",
            "Mürekkep",
            "Batarya",
            "tedavi",
            "nail polish",
            "oje",
            "Teşekkürler",
        ];
        $map = array_map('preg_quote', $map);
        $map = implode('|', $map);
        //先清除完全匹配的
        $content = preg_replace('/\b(' . $map . ')\b/iu', '', $content);
        $content = str_replace('  ', ' ', $content);
        return $content;
    }
}